version: '3.8'

services:

  traefik:
    image: traefik:2.8
    env_file:
      - .env
    networks:
      - global
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DATA_DIR}/traefik/traefik.toml:/etc/traefik/traefik.toml
      - ${DATA_DIR}/traefik/acme.json:/acme.json
      - ${DATA_DIR}/traefik/.htpasswd:/.htpasswd
    labels:
      - "traefik.http.middlewares.basic-auth.basicauth.usersfile=/.htpasswd"

networks:
  global:
    external: true
